### ISSUE TITLE
`carti which` option to return only asset path

### ISSUE THREAD

**Issue by miltonjonat** [createdreamtech/carti#15]
The `which` commands currently returns assets in the format `<name>:<cid>:<version>:<asset-path>`

We could add an option `-p`, `--path-only` (or just `--path`) so that only `<asset-path>` is returned. This would be useful in order to easily integrate Carti bundles with the regular `cartesi-machine` utility or other scripts.

For example:
```bash
cartesi-machine \
 --flash-drive="label:scrypt-hash,filename:$(carti which -p -y scrypt-hash)" \
 --flash-drive="label:input,length:1<<12" \
 --flash-drive="label:output,length:1<<12" \
 -- $'cd /mnt/scrypt-hash ; ./scrypt-hash $(flashdrive input) $(flashdrive output)'
```

**Comment by zcstarr** [comment]
Thinking about this one I think you were on to the right path with the original name you shared. get. 


maybe which stays with a -p option and get is added

```bash
cartesi-machine \
 --flash-drive="label:scrypt-hash,filename:$(carti get -p -y scrypt-hash)" \
 --flash-drive="label:input,length:1<<12" \
 --flash-drive="label:output,length:1<<12" \
 -- $'cd /mnt/scrypt-hash ; ./scrypt-hash $(flashdrive input) $(flashdrive output)'
```
That way there are these three commands
install - that always installs
get - that installs if it's not local
which - locates what's installed if it's installed

**Comment by miltonjonat** [comment]
So `get` would be `install` + `which`? Its output would be the same as `which`, with the same parameters (in this case `-p` and `-y`)?

**Comment by miltonjonat** [comment]
So, I just checked the lastest release (0.4.0) and noticed that `which` is there but without the `-p`, `-y` options. Don't know if this was the intended result - but I don't have a strong opinion about it really
