### ISSUE TITLE
`carti machine add`: handling drive labels and drives with no associated bundles

### ISSUE THREAD

**Issue by miltonjonat** [createdreamtech/carti#30]
When using the `cartesi-machine` tool, it is actually *mandatory* to define a drive's label. It is also a common use case to define a drive with no associated bundle, which means that the content will be defined on instantiation (this is the common procedure for use with the Descartes smart contract)

To account for these requirements, a new format for this command could be the following:
```
carti machine add flash [options] <label>
````
where:
- `[options]` would now include `--bundle`
- It would be mandatory to specify either `--bundle` or `--length`
- Examples:
  - `carti machine add flash --length 0x1000 input`
  - `carti machine add flash --bundle scrypt-hash my-util`

**Comment by zcstarr** [comment]
this is fixed by #42
