### ISSUE TITLE
Remove `carti machine build` command

### ISSUE THREAD

**Issue by miltonjonat** [createdreamtech/carti#37]
We will no longer build stored machines, and `carti machine install` will probably be enough for our needs

**Comment by zcstarr** [comment]
Changing the semantics of things. So I think build still exists, it just means to build your machine.json into a lua cartesi machine. 

While install will resolve a machine.json and  produce cartesi machine config. 

Typing htis there is some overlap but there might be some more clarity in just having the ability to do one quickly and not the other. So I think it's a we'll see putting in a fix now that does the conversion
