### ISSUE TITLE
`carti machine repo add` does not seem to work

### ISSUE THREAD

**Issue by miltonjonat** [createdreamtech/carti#71]
Affecting carti 1.6.7
```
$ carti machine repo list
https://github.com/createdreamtech/carti-default
$ carti machine repo add https://github.com/createdreamtech/carti-sample/tree/feat/complete
$ carti machine repo list
https://github.com/createdreamtech/carti-default
```

**Comment by zcstarr** [comment]
Just realizing this might be a bit confusing and awkward. in this case machine repo list is only listing the computed  repos based off of the cids in the config. It doesn't list what exists in the config, so if you add repo that is not a strict dependency of the cid then machine repo list will not show that repo. 

I might need a separate arg or option for listing strictly computed dependencies vs what's currently in the json.

**Comment by miltonjonat** [comment]
Not sure I get it, let me know if this is how it works and if my comments/suggestions make sense:
- The carti machine JSON contains a listing of repos, which basically serves to instruct `carti machine install` to add that repo before attempting to fetch the bundles. Is that right?
- In that context, `carti machine repo list` does not show that listing, but rather where the machine's assets are actually found in the current environment's repos? If that's the case then yeah, I think an option would be nice here. And I would add that, at first glance, maybe just listing the explicitly specified repos could be the default (most intuitive) behavior.
- I just noticed that `carti machine repo add` does not really *add* to the existing listing, but rather sets the entire repo listing entry to the provided list. I feel this is also not so intuitive, especially when we compare with `carti repo add`. Maybe it would be better to either really add (append) the new repo or repos to the existing listing, or else preserve the current behavior but change the command to `carti machine repo set`. I personally prefer `add`, which I think is easier to use and more consistent with `carti repo`. In that case, `carti machine repo rm` would remove a given repo as well, and entire repo entry could be removed if the last repo is removed. Anyway, just some suggestions.

**Comment by zcstarr** [comment]
I think you're right about add not being intuitive. I'm in favor of just having set , renaming list to deps, and creating a new list that just lists all the repos. I think that this will help things be alot more intuitive. 

The initial use case thought was, that you might have drives from many different repos, and you need a way 
to specify that you want to make the storage location of those drives public.  You could then just call 
```
carti machine set $(carti machine repo deps)
```
And with the improved list you would then be able to add additional repos to the existing set fairly easily as well as rm
```

**Comment by zcstarr** [comment]
I went back and forth on this a bit :) . So I went with add and remove , your example sold me on it.
The other thing here is a refactored list semantics so there's list and deps, and add/rm supports repo now.
