### ISSUE TITLE
Remove `-f` option in `carti bundle`?

### ISSUE THREAD

**Issue by miltonjonat** [createdreamtech/carti#74]
Not sure what it stands for, since the mandatory `<src>` argument already specifies the asset. Or is there a catch?

```
$ carti bundle --help
Usage: carti bundle [options] <src>

Bundle data for a cartesi machine src is a url payload or filepath

Options:
  -t, --type <type>        input type of data ram|rom|flashdrive
  -n, --name <name>        name of the bundle
  -v, --version <version>  version of the bundle
  -d, --desc <desc>        description of the bundle
  -f, --filename [name]    name of the bundle              <------------
  -h, --help               display help for command
```

**Comment by zcstarr** [comment]
There's a catch, right now it's reliant on the headers specifying file-content type. Which might not always be the case depending on storage plugin type. 

So we may not have all the information all the time to just infer the filename so users get to opt out.

**Comment by miltonjonat** [comment]
Hmm, not quite sure I followed there. But at least the description (`f, --filename [name]    name of the bundle`) is surely wrong isn't it? Maybe you could elaborate on this file-content type issue there on the description?

**Comment by zcstarr** [comment]
Yeah I should elaborate in the comment. It's an attempt to avoid storage or retrieval lockin.  
My thought is that let's say there's a storage type or plugin, that uses a different protocol than http. We may not be able to automatically retrieve a sensible filename.

 It's possible that filename metadata isn't written into the data coming over the wire. With http that happens to be often included in the response headers. 
 
 I'm going to patch up the description to be a bit more verbose and clear there. and definitely not duplicate the --name message
