### ISSUE TITLE
Bundle type `flash` vs `flashdrive`

### ISSUE THREAD

**Issue by miltonjonat** [createdreamtech/carti#75]
The `default-root` asset comes with type `flash`, but `carti bundle`'s help refers to type `flashdrive`

**Comment by zcstarr** [comment]
Nice catch I"ll patch this up!

**Comment by zcstarr** [comment]
This was actually fixed a while back with the incorrect metadata my guess is the default package pulled down is stale. I changed it prior to the first announced release. 

https://github.com/createdreamtech/carti-default/commit/1094b29cf5fe1c041a4923f54bd84559dd228e32
